#!/usr/bin/env bash
# shellcheck disable=SC2086
# display information about subdomains

display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain =  "$1"
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        display_info "$subdomain" "$domain"
    done
elif [ $# -eq 2 ]; then
    subdomain = "$2"
    domain = "$1"
    display_info "$subdomain" "$domain"
fi
