#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#+  Configure HAproxy so that it send traffic to web-01 and web-02
#+  Distribute requests using a roundrobin algorithm
#+   Make sure that HAproxy can be managed via an init script

apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
HAPROXYCONFIG="
frontend haproxy-main
        bind *:80
        mode http
        default_backend task-servers
backend task-servers
        balance roundrobin
        server 10718-web-01 54.165.235.40:80 check
        server 10718-web-02 54.144.148.54:80 check
"

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
echo "$HAPROXYCONFIG" >> /etc/haproxy/haproxy.cfg
service haproxy restart
